export const metadata = {
  title: "Play Store || Installation",
  description: "Generated by create next app",
};

const Installation = () => {
    return (
        <div>
            <h1 className="text-3xl font-bold text-center mt-10">Installation Page</h1>
        </div>
    );
};

export default Installation;