export const metadata = {
  title: "Play Store || Dashboard",
  description: "Generated by create next app",
};

const DashBoard = () => {
    return (
        <div>
            <h1 className="text-3xl font-bold text-center mt-10">Dashboard Page</h1>
        </div>
    );
};

export default DashBoard;