import React from "react";
import { use } from "react";
import Image from "next/image";
import Link from "next/link";
import { FiDownload } from "react-icons/fi";
import { FaStar } from "react-icons/fa";
import { RiChatVoiceLine } from "react-icons/ri";
import { IoArrowBackOutline } from "react-icons/io5";
import InstallButton from "../InstallButton";


export const metadata = {
    title: "Play Store || App Details",
    description: "Generated by create next app",
};

export const dynamic = 'force-dynamic';


const AppDetails = async ({ params }) => {
    const { slug } = await params;
    const response = await fetch(`http://localhost:3000/data.json`);
    const allData = await response.json();
    const data = allData.find(app => app.id === Number(slug));

    console.log(slug);
    console.log("data:", data);

    const ratingList = data?.ratings || [];
    const maxRatingCount = Math.max(...ratingList.map(r => r.count), 1);
    const descriptionParts = data?.description?.split('\n').filter(p => p.trim()) || [];
    return (
        <section className="bg-[#efefef] py-6 md:py-12 lg:py-16">
            <div className="max-w-6xl mx-auto px-4">
                <div className="border border-gray-300 p-3 md:p-6 bg-white">
                    {data ? (
                        <>
                            <div className="grid grid-cols-1 md:grid-cols-12 gap-3 md:gap-6">
                                <div className="md:col-span-2">
                                    <div className="h-24 w-24 sm:h-28 sm:w-28 md:h-32 md:w-32 bg-white border border-gray-200 rounded overflow-hidden p-2 mx-auto md:mx-0 flex-shrink-0 relative">
                                        <Image
                                            src={data.image}
                                            alt={data.title}
                                            fill
                                            className="object-contain p-2"
                                        />
                                    </div>
                                </div>

                                <div className="md:col-span-9 lg:col-span-10">
                                    <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-2 md:gap-3">
                                        <h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl leading-tight font-extrabold text-[#0B2945]">{data.title}</h1>
                                        <Link
                                            href="/Apps"
                                            className="inline-flex items-center gap-2 bg-transparent border border-[#0B2945]/30 text-[#0B2945] px-3 md:px-4 py-1.5 md:py-2 rounded-md text-xs md:text-sm font-semibold hover:bg-[#0B2945]/8 transition-colors w-fit"
                                        >
                                            <IoArrowBackOutline className="text-base md:text-lg" />
                                        </Link>
                                    </div>
                                    <p className="mt-1 md:mt-2 text-xs md:text-sm text-gray-500">
                                        Developed by <span className="text-violet-600">{data.companyName}</span>
                                    </p>

                                    <div className="mt-3 md:mt-4 border-t border-gray-300 pt-3 md:pt-4">
                                        <div className="grid grid-cols-3 gap-2 md:gap-4">
                                            <div>
                                                <FiDownload className="text-[#10b981] text-lg md:text-xl" />
                                                <p className="text-[10px] md:text-xs text-gray-500 mt-1">Downloads</p>
                                                <p className="text-lg md:text-2xl lg:text-4xl leading-none font-extrabold text-[#0B2945] mt-1">{data.downloads}</p>
                                            </div>

                                            <div>
                                                <FaStar className="text-[#f59e0b] text-lg md:text-xl" />
                                                <p className="text-[10px] md:text-xs text-gray-500 mt-1">Average Ratings</p>
                                                <p className="text-lg md:text-2xl lg:text-4xl leading-none font-extrabold text-[#0B2945] mt-1">{data.ratingAvg}</p>
                                            </div>

                                            <div>
                                                <RiChatVoiceLine className="text-violet-600 text-lg md:text-xl" />
                                                <p className="text-[10px] md:text-xs text-gray-500 mt-1">Total Reviews</p>
                                                <p className="text-lg md:text-2xl lg:text-4xl leading-none font-extrabold text-[#0B2945] mt-1">{data.reviews}</p>
                                            </div>
                                        </div>

                                        <InstallButton app={data} />
                                    </div>
                                </div>
                            </div>

                            <div className="mt-6 border-t border-gray-300 pt-4">
                                <h2 className="text-lg md:text-2xl lg:text-[28px] font-bold text-[#0B2945]">Ratings</h2>

                                <div className="mt-4 space-y-2 md:space-y-3">
                                    {ratingList.map((item) => (
                                        <div key={item.name} className="grid grid-cols-[40px,1fr] md:grid-cols-[56px,1fr] items-center gap-2 md:gap-3">
                                            <p className="text-xs md:text-sm text-gray-500">{item.name}</p>
                                            <div className="h-4 md:h-5">
                                                <div
                                                    className="h-full bg-[#ff8a00]"
                                                    style={{ width: `${(item.count / maxRatingCount) * 100}%` }}
                                                />
                                            </div>
                                        </div>
                                    ))}
                                </div>

                                <div className="mt-2 md:mt-3 flex justify-between text-[10px] md:text-xs text-gray-500 pl-12 md:pl-17">
                                    <span>0</span>
                                    <span>3000</span>
                                    <span>6000</span>
                                    <span>9000</span>
                                    <span>12000</span>
                                </div>
                            </div>

                            <div className="mt-6 border-t border-gray-300 pt-4">
                                <h2 className="text-lg md:text-2xl lg:text-[28px] font-bold text-[#0B2945]">Description</h2>

                                <div className="mt-4 space-y-3 md:space-y-5 text-gray-600 leading-6 md:leading-8 text-sm md:text-base">
                                    {descriptionParts.map((paragraph, index) => (
                                        <p key={index}>{paragraph}</p>
                                    ))}
                                </div>
                            </div>
                        </>
                    ) : (
                        <p className="text-center text-gray-500">App not found</p>
                    )}
                </div>
            </div>
        </section>
    );
};

export default AppDetails;