

export const metadata = {
  title: "Play Store || App Details",
  description: "Generated by create next app",
};


const AppDetails = () => {

    
    return (
        <div>
            <h1>App Details</h1>
            
        </div>
    );
};

export default AppDetails;